#!/bin/sh

BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

$BASEDIR/build/install/hoptimator-mcp-server/bin/hoptimator-mcp-server \
  -Dorg.slf4j.simpleLogger.showThreadName=false \
  -Dorg.slf4j.simpleLogger.showLogName=false \
  com.linkedin.hoptimator.mcp.server.HoptimatorMcpServer

