#!/bin/sh

BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

$BASEDIR/hoptimator-cli/build/install/hoptimator-cli/bin/hoptimator-cli \
  -Dorg.slf4j.simpleLogger.showThreadName=false \
  -Dorg.slf4j.simpleLogger.showLogName=false \
  sqlline.SqlLine \
  -ac sqlline.HoptimatorAppConfig \
  --verbose \
  -u "jdbc:hoptimator://fun=mysql;hints=offline.table.name=ads_offline,job.properties.account=foo,venice.test-store.valueSchemaId=1" -n "" -p "" -nn "Hoptimator" $@

