#!/bin/sh

BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

$BASEDIR/hoptimator-mcp-server-app/build/install/hoptimator-mcp-server-app/bin/hoptimator-mcp-server-app \
  -Dorg.slf4j.simpleLogger.showThreadName=false \
  -Dorg.slf4j.simpleLogger.showLogName=false \
  com.linkedin.hoptimator.mcp.server.HoptimatorMcpServer "jdbc:hoptimator://fun=mysql"
