apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
    - db
    - dbs
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Database metadata.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: Database spec.
              type: object
              properties:
                url:
                  description: JDBC connection URL
                  type: string
                catalog:
                  description: JDBC catalog name (optional, for hierarchical sources like MySQL).
                  type: string
                schema:
                  description: Schema name, as rendered in the catalog.
                  type: string
                dialect:
                  description: SQL dialect the driver expects.
                  type: string
                  enum:
                  - ANSI
                  - MySQL
                  - Calcite
                driver:
                  description: Fully qualified class name of JDBC driver.
                  type: string
              required:
              - url
            status:
              type: object
              properties:
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: SCHEMA
        type: string
        description: Schema name.
        jsonPath: .spec.schema
      - name: URL
        type: string
        description: JDBC URL.
        jsonPath: .spec.url
