apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: engines.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: Engine
    listKind: EngineList
    plural: engines
    singular: engine
    shortNames:
    - eng
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Engine metadata.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: Engine spec.
              type: object
              properties:
                url:
                  description: JDBC connection URL
                  type: string
                dialect:
                  description: SQL dialect the driver expects.
                  type: string
                  enum:
                  - ANSI
                  - MySQL
                  - Calcite
                driver:
                  description: Fully qualified class name of JDBD driver.
                  type: string
                databases:
                  description: Databases this engine supports. If null, supports everything.
                  type: array
                  items:
                    type: string
              required:
              - url
            status:
              type: object
              properties: 
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: URL
        type: string
        description: JDBC URL.
        jsonPath: .spec.url
