apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: JobTemplate
    listKind: JobTemplateList
    plural: jobtemplates
    singular: jobtemplate
    shortNames:
    - jobt
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Template to apply to matching jobs.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: JobTemplate spec.
              type: object
              properties:
                yaml:
                  description: YAML template used to generate K8s specs.
                  type: string
                databases:
                  description: Databases this template matches. If null, matches everything.
                  type: array
                  items:
                    type: string

