apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
    shortNames:
    - pip
    - pips
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A set of objects that work together to deliver data.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: Pipeline spec.
              type: object
              properties:
                sql:
                  description: The INSERT INTO statement this pipeline implements.
                  type: string
                yaml:
                  description: The objects that make up the pipeline.
                  type: string
              required:
            status:
              description: Pipeline status.
              type: object
              properties:
                ready:
                  description: Whether the entire pipeline is ready.
                  type: boolean
                failed:
                  description: Whether any part of the pipeline has failed.
                  type: boolean
                message:
                  description: Error or success message, for information only.
                  type: string
                jobs:
                  type: object
                  description: External jobs that this pipeline triggers.
                  additionalProperties:
                    type: object
                    description: Properties of the job.
                    additionalProperties:
                      type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: SQL
        type: string
        description: Pipeline SQL.
        jsonPath: .spec.sql
      - name: STATUS
        type: string
        description: Status message.
        jsonPath: .status.message


