apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqljobs.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: SqlJob
    listKind: SqlJobList
    plural: sqljobs
    singular: sqljob
    shortNames:
    - sql
    - sj
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Hoptimator generic SQL job
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: SQL job spec
              type: object
              properties:
                sql:
                  description: SQL script the job should run.
                  type: array
                  items:
                    type: string
                dialect:
                  description: Flink, etc.
                  type: string
                  enum:
                  - Flink
                  default: Flink
                executionMode:
                  description: Streaming or Batch.
                  type: string
                  enum:
                  - Streaming
                  - Batch
                  default: Streaming
                configs:
                  description: SQL Job configurations.
                  type: object
                  additionalProperties:
                    type: string
              required:
              - sql
            status:
              description: Filled in by the operator.
              type: object
              properties:
                ready:
                  description: Whether the SqlJob is running or completed.
                  type: boolean
                failed:
                  description: Whether the SqlJob has failed.
                  type: boolean
                message:
                  description: Error or success message, for information only.
                  type: string
                sql:
                  description: The SQL being implemented by this SqlJob.
                  type: string
                configs:
                  description: The SQL configurations used by this SqlJob.
                  type: object
                  additionalProperties:
                    type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: DIALECT
        type: string
        description: SQL dialect.
        jsonPath: .spec.dialect
      - name: MODE
        type: string
        description: Execution mode.
        jsonPath: .spec.executionMode
      - name: STATUS
        type: string
        description: Job status.
        jsonPath: .status.message

