apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tabletriggers.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: TableTrigger
    listKind: TableTriggerList
    plural: tabletriggers
    singular: tabletrigger
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Trigger for a specific table.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: TableTrigger spec.
              type: object
              properties:
                schema:
                  description: The schema the table belongs to, e.g. KAFKA.
                  type: string
                table:
                  description: The table name, e.g. PageViewEvent.
                  type: string
                operations:
                  description: Specific operations this trigger matches. If null, matches all operations.
                  type: array
                  items:
                    type: string
                    enum:
                    - Delete
                    - Insert
                    - Update
                yaml:
                  description: Specifies the Job to re/create when the trigger fires.
                  type: string
              required:
              - schema
              - table
            status:
              description: TableTrigger status.
              type: object
              properties:
                timestamp:
                  description: Time at which the trigger was last fired.
                  type: string
                  format: date-time
                watermark:
                  description: Timestamp of the last successfully processed trigger event.
                  type: string
                  format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: SCHEMA
        type: string
        description: Schema name.
        jsonPath: .spec.schema
      - name: TABLE
        type: string
        description: Table name.
        jsonPath: .spec.table
      - name: TIMESTAMP
        type: string
        description: Time last fired.
        format: date-time
        jsonPath: .status.timestamp
      - name: WATERMARK
        type: string
        description: Last successful timestamp.
        format: date-time
        jsonPath: .status.watermark

