apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tabletemplates.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: TableTemplate
    listKind: TableTemplateList
    plural: tabletemplates
    singular: tabletemplate
    shortNames:
    - tmpl
    - tmpls
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Template to apply to matching tables.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: TableTemplate spec.
              type: object
              properties:
                yaml:
                  description: YAML template used to generate K8s specs.
                  type: string
                connector:
                  description: Config template used to generate connector configs.
                  type: string
                databases:
                  description: Databases this template matches. If null, matches everything.
                  type: array
                  items:
                    type: string
                methods:
                  description: Table access methods this template matches. If null, matches any access method.
                  type: array
                  items:
                    type: string
                    enum:
                    - Scan
                    - Modify

