apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: views.hoptimator.linkedin.com
spec:
  group: hoptimator.linkedin.com
  names:
    kind: View
    listKind: ViewList
    plural: views
    singular: view
    shortNames:
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A SQL view.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: View spec.
              type: object
              properties:
                catalog:
                  description: Catalog name.
                  type: string
                schema:
                  description: Schema name.
                  type: string
                view:
                  description: View name.
                  type: string
                sql:
                  description: View SQL.
                  type: string
                materialized:
                  description: Whether the view should be materialized.
                  type: boolean
              required:
              - view
              - sql
            status:
              type: object
              properties:
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: SCHEMA
        type: string
        description: Schema name.
        jsonPath: .spec.schema
      - name: VIEW
        type: string
        description: View name.
        jsonPath: .spec.view
      - name: SQL
        type: string
        description: View SQL.
        jsonPath: .spec.sql

