/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Tier binding for a logical table.
 */
@ApiModel(description = "Tier binding for a logical table.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class V1alpha1LogicalTableTier {
  public static final String SERIALIZED_NAME_DATABASE_CRD_NAME = "databaseCrdName";
  @SerializedName(SERIALIZED_NAME_DATABASE_CRD_NAME)
  private String databaseCrdName;


  public V1alpha1LogicalTableTier databaseCrdName(String databaseCrdName) {
    this.databaseCrdName = databaseCrdName;
    return this;
  }

  /**
   * Name of the Database CRD backing this tier.
   * @return databaseCrdName
   */
  @ApiModelProperty(required = true, value = "Name of the Database CRD backing this tier.")
  public String getDatabaseCrdName() {
    return databaseCrdName;
  }

  public void setDatabaseCrdName(String databaseCrdName) {
    this.databaseCrdName = databaseCrdName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableTier that = (V1alpha1LogicalTableTier) o;
    return Objects.equals(this.databaseCrdName, that.databaseCrdName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseCrdName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableTier {\n");
    sb.append("    databaseCrdName: ").append(toIndentedString(databaseCrdName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
