/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * V1alpha1ViewStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-06T19:55:05.553Z[Etc/UTC]")
public class V1alpha1ViewStatus {
  public static final String SERIALIZED_NAME_WATERMARK = "watermark";
  @SerializedName(SERIALIZED_NAME_WATERMARK)
  private OffsetDateTime watermark;


  public V1alpha1ViewStatus watermark(OffsetDateTime watermark) {
    
    this.watermark = watermark;
    return this;
  }

   /**
   * Timestamp of last data change event affecting this view.
   * @return watermark
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timestamp of last data change event affecting this view.")

  public OffsetDateTime getWatermark() {
    return watermark;
  }


  public void setWatermark(OffsetDateTime watermark) {
    this.watermark = watermark;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ViewStatus v1alpha1ViewStatus = (V1alpha1ViewStatus) o;
    return Objects.equals(this.watermark, v1alpha1ViewStatus.watermark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(watermark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ViewStatus {\n");
    sb.append("    watermark: ").append(toIndentedString(watermark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

