/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * TableTrigger status.
 */
@ApiModel(description = "TableTrigger status.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T18:33:48.223Z[Etc/UTC]")
public class V1alpha1TableTriggerStatus {
  public static final String SERIALIZED_NAME_JOBS = "jobs";
  @SerializedName(SERIALIZED_NAME_JOBS)
  private Map<String, Map<String, String>> jobs = null;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_WATERMARK = "watermark";
  @SerializedName(SERIALIZED_NAME_WATERMARK)
  private OffsetDateTime watermark;


  public V1alpha1TableTriggerStatus jobs(Map<String, Map<String, String>> jobs) {
    
    this.jobs = jobs;
    return this;
  }

  public V1alpha1TableTriggerStatus putJobsItem(String key, Map<String, String> jobsItem) {
    if (this.jobs == null) {
      this.jobs = new HashMap<>();
    }
    this.jobs.put(key, jobsItem);
    return this;
  }

   /**
   * State of jobs triggered by this trigger.
   * @return jobs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "State of jobs triggered by this trigger.")

  public Map<String, Map<String, String>> getJobs() {
    return jobs;
  }


  public void setJobs(Map<String, Map<String, String>> jobs) {
    this.jobs = jobs;
  }


  public V1alpha1TableTriggerStatus timestamp(OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Time at which the trigger was last fired.
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Time at which the trigger was last fired.")

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public V1alpha1TableTriggerStatus watermark(OffsetDateTime watermark) {
    
    this.watermark = watermark;
    return this;
  }

   /**
   * Timestamp of the last successfully processed trigger event.
   * @return watermark
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timestamp of the last successfully processed trigger event.")

  public OffsetDateTime getWatermark() {
    return watermark;
  }


  public void setWatermark(OffsetDateTime watermark) {
    this.watermark = watermark;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1TableTriggerStatus v1alpha1TableTriggerStatus = (V1alpha1TableTriggerStatus) o;
    return Objects.equals(this.jobs, v1alpha1TableTriggerStatus.jobs) &&
        Objects.equals(this.timestamp, v1alpha1TableTriggerStatus.timestamp) &&
        Objects.equals(this.watermark, v1alpha1TableTriggerStatus.watermark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobs, timestamp, watermark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1TableTriggerStatus {\n");
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    watermark: ").append(toIndentedString(watermark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

