/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkedin.hoptimator.k8s.models.V1alpha1LogicalTableSpecPipelines;
import com.linkedin.hoptimator.k8s.models.V1alpha1LogicalTableSpecTiers;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Desired logical table configuration.
 */
@ApiModel(description = "Desired logical table configuration.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T18:33:48.223Z[Etc/UTC]")
public class V1alpha1LogicalTableSpec {
  public static final String SERIALIZED_NAME_AVRO_SCHEMA = "avroSchema";
  @SerializedName(SERIALIZED_NAME_AVRO_SCHEMA)
  private String avroSchema;

  public static final String SERIALIZED_NAME_PIPELINES = "pipelines";
  @SerializedName(SERIALIZED_NAME_PIPELINES)
  private List<V1alpha1LogicalTableSpecPipelines> pipelines = null;

  public static final String SERIALIZED_NAME_TIERS = "tiers";
  @SerializedName(SERIALIZED_NAME_TIERS)
  private Map<String, V1alpha1LogicalTableSpecTiers> tiers = null;


  public V1alpha1LogicalTableSpec avroSchema(String avroSchema) {
    
    this.avroSchema = avroSchema;
    return this;
  }

   /**
   * Canonical Avro schema JSON for the table.
   * @return avroSchema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Canonical Avro schema JSON for the table.")

  public String getAvroSchema() {
    return avroSchema;
  }


  public void setAvroSchema(String avroSchema) {
    this.avroSchema = avroSchema;
  }


  public V1alpha1LogicalTableSpec pipelines(List<V1alpha1LogicalTableSpecPipelines> pipelines) {
    
    this.pipelines = pipelines;
    return this;
  }

  public V1alpha1LogicalTableSpec addPipelinesItem(V1alpha1LogicalTableSpecPipelines pipelinesItem) {
    if (this.pipelines == null) {
      this.pipelines = new ArrayList<>();
    }
    this.pipelines.add(pipelinesItem);
    return this;
  }

   /**
   * List of implicit inter-tier pipelines created for this table.
   * @return pipelines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of implicit inter-tier pipelines created for this table.")

  public List<V1alpha1LogicalTableSpecPipelines> getPipelines() {
    return pipelines;
  }


  public void setPipelines(List<V1alpha1LogicalTableSpecPipelines> pipelines) {
    this.pipelines = pipelines;
  }


  public V1alpha1LogicalTableSpec tiers(Map<String, V1alpha1LogicalTableSpecTiers> tiers) {
    
    this.tiers = tiers;
    return this;
  }

  public V1alpha1LogicalTableSpec putTiersItem(String key, V1alpha1LogicalTableSpecTiers tiersItem) {
    if (this.tiers == null) {
      this.tiers = new HashMap<>();
    }
    this.tiers.put(key, tiersItem);
    return this;
  }

   /**
   * Map of tier name to tier binding.
   * @return tiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of tier name to tier binding.")

  public Map<String, V1alpha1LogicalTableSpecTiers> getTiers() {
    return tiers;
  }


  public void setTiers(Map<String, V1alpha1LogicalTableSpecTiers> tiers) {
    this.tiers = tiers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableSpec v1alpha1LogicalTableSpec = (V1alpha1LogicalTableSpec) o;
    return Objects.equals(this.avroSchema, v1alpha1LogicalTableSpec.avroSchema) &&
        Objects.equals(this.pipelines, v1alpha1LogicalTableSpec.pipelines) &&
        Objects.equals(this.tiers, v1alpha1LogicalTableSpec.tiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avroSchema, pipelines, tiers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableSpec {\n");
    sb.append("    avroSchema: ").append(toIndentedString(avroSchema)).append("\n");
    sb.append("    pipelines: ").append(toIndentedString(pipelines)).append("\n");
    sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

