/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Logical table spec.
 */
@ApiModel(description = "Logical table spec.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class V1alpha1LogicalTableSpec {
  public static final String SERIALIZED_NAME_AVRO_SCHEMA = "avroSchema";
  @SerializedName(SERIALIZED_NAME_AVRO_SCHEMA)
  private String avroSchema;

  public static final String SERIALIZED_NAME_TIERS = "tiers";
  @SerializedName(SERIALIZED_NAME_TIERS)
  private Map<String, V1alpha1LogicalTableTier> tiers;

  public static final String SERIALIZED_NAME_PIPELINES = "pipelines";
  @SerializedName(SERIALIZED_NAME_PIPELINES)
  private List<V1alpha1LogicalTablePipeline> pipelines = new ArrayList<>();


  public V1alpha1LogicalTableSpec avroSchema(String avroSchema) {
    this.avroSchema = avroSchema;
    return this;
  }

  /**
   * Canonical Avro schema JSON for the table.
   * @return avroSchema
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Canonical Avro schema JSON for the table.")
  public String getAvroSchema() {
    return avroSchema;
  }

  public void setAvroSchema(String avroSchema) {
    this.avroSchema = avroSchema;
  }


  public V1alpha1LogicalTableSpec tiers(Map<String, V1alpha1LogicalTableTier> tiers) {
    this.tiers = tiers;
    return this;
  }

  public V1alpha1LogicalTableSpec putTiersItem(String key, V1alpha1LogicalTableTier tier) {
    if (this.tiers == null) {
      this.tiers = new java.util.LinkedHashMap<>();
    }
    this.tiers.put(key, tier);
    return this;
  }

  /**
   * Map of tier name to tier binding.
   * @return tiers
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of tier name to tier binding.")
  public Map<String, V1alpha1LogicalTableTier> getTiers() {
    return tiers;
  }

  public void setTiers(Map<String, V1alpha1LogicalTableTier> tiers) {
    this.tiers = tiers;
  }


  public V1alpha1LogicalTableSpec pipelines(List<V1alpha1LogicalTablePipeline> pipelines) {
    this.pipelines = pipelines;
    return this;
  }

  public V1alpha1LogicalTableSpec addPipelinesItem(V1alpha1LogicalTablePipeline pipeline) {
    if (this.pipelines == null) {
      this.pipelines = new ArrayList<>();
    }
    this.pipelines.add(pipeline);
    return this;
  }

  /**
   * List of implicit inter-tier pipelines created for this table.
   * @return pipelines
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of implicit inter-tier pipelines created for this table.")
  public List<V1alpha1LogicalTablePipeline> getPipelines() {
    return pipelines;
  }

  public void setPipelines(List<V1alpha1LogicalTablePipeline> pipelines) {
    this.pipelines = pipelines;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableSpec that = (V1alpha1LogicalTableSpec) o;
    return Objects.equals(this.avroSchema, that.avroSchema)
        && Objects.equals(this.tiers, that.tiers)
        && Objects.equals(this.pipelines, that.pipelines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avroSchema, tiers, pipelines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableSpec {\n");
    sb.append("    avroSchema: ").append(toIndentedString(avroSchema)).append("\n");
    sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
    sb.append("    pipelines: ").append(toIndentedString(pipelines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
