/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1LogicalTableSpecPipelines
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T18:33:48.223Z[Etc/UTC]")
public class V1alpha1LogicalTableSpecPipelines {
  public static final String SERIALIZED_NAME_FROM_TIER = "fromTier";
  @SerializedName(SERIALIZED_NAME_FROM_TIER)
  private String fromTier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PIPELINE_CRD_NAME = "pipelineCrdName";
  @SerializedName(SERIALIZED_NAME_PIPELINE_CRD_NAME)
  private String pipelineCrdName;

  public static final String SERIALIZED_NAME_TO_TIER = "toTier";
  @SerializedName(SERIALIZED_NAME_TO_TIER)
  private String toTier;


  public V1alpha1LogicalTableSpecPipelines fromTier(String fromTier) {
    
    this.fromTier = fromTier;
    return this;
  }

   /**
   * Source tier name.
   * @return fromTier
  **/
  @ApiModelProperty(required = true, value = "Source tier name.")

  public String getFromTier() {
    return fromTier;
  }


  public void setFromTier(String fromTier) {
    this.fromTier = fromTier;
  }


  public V1alpha1LogicalTableSpecPipelines name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Pipeline name, e.g. __logical-foo-nearline-to-online.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Pipeline name, e.g. __logical-foo-nearline-to-online.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1LogicalTableSpecPipelines pipelineCrdName(String pipelineCrdName) {
    
    this.pipelineCrdName = pipelineCrdName;
    return this;
  }

   /**
   * Name of the Pipeline CRD.
   * @return pipelineCrdName
  **/
  @ApiModelProperty(required = true, value = "Name of the Pipeline CRD.")

  public String getPipelineCrdName() {
    return pipelineCrdName;
  }


  public void setPipelineCrdName(String pipelineCrdName) {
    this.pipelineCrdName = pipelineCrdName;
  }


  public V1alpha1LogicalTableSpecPipelines toTier(String toTier) {
    
    this.toTier = toTier;
    return this;
  }

   /**
   * Sink tier name.
   * @return toTier
  **/
  @ApiModelProperty(required = true, value = "Sink tier name.")

  public String getToTier() {
    return toTier;
  }


  public void setToTier(String toTier) {
    this.toTier = toTier;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableSpecPipelines v1alpha1LogicalTableSpecPipelines = (V1alpha1LogicalTableSpecPipelines) o;
    return Objects.equals(this.fromTier, v1alpha1LogicalTableSpecPipelines.fromTier) &&
        Objects.equals(this.name, v1alpha1LogicalTableSpecPipelines.name) &&
        Objects.equals(this.pipelineCrdName, v1alpha1LogicalTableSpecPipelines.pipelineCrdName) &&
        Objects.equals(this.toTier, v1alpha1LogicalTableSpecPipelines.toTier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromTier, name, pipelineCrdName, toTier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableSpecPipelines {\n");
    sb.append("    fromTier: ").append(toIndentedString(fromTier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pipelineCrdName: ").append(toIndentedString(pipelineCrdName)).append("\n");
    sb.append("    toTier: ").append(toIndentedString(toTier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

