/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkedin.hoptimator.k8s.models.V1alpha1LogicalTableSpecTiers;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Desired logical table configuration.
 */
@ApiModel(description = "Desired logical table configuration.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-19T19:18:59.968Z[Etc/UTC]")
public class V1alpha1LogicalTableSpec {
  public static final String SERIALIZED_NAME_TABLE_NAME = "tableName";
  @SerializedName(SERIALIZED_NAME_TABLE_NAME)
  private String tableName;

  public static final String SERIALIZED_NAME_TIERS = "tiers";
  @SerializedName(SERIALIZED_NAME_TIERS)
  private Map<String, V1alpha1LogicalTableSpecTiers> tiers = null;


  public V1alpha1LogicalTableSpec tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Original table name as declared in CREATE TABLE (e.g. \&quot;testevent\&quot;).
   * @return tableName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Original table name as declared in CREATE TABLE (e.g. \"testevent\").")

  public String getTableName() {
    return tableName;
  }


  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  public V1alpha1LogicalTableSpec tiers(Map<String, V1alpha1LogicalTableSpecTiers> tiers) {
    
    this.tiers = tiers;
    return this;
  }

  public V1alpha1LogicalTableSpec putTiersItem(String key, V1alpha1LogicalTableSpecTiers tiersItem) {
    if (this.tiers == null) {
      this.tiers = new HashMap<>();
    }
    this.tiers.put(key, tiersItem);
    return this;
  }

   /**
   * Map of tier name to tier binding.
   * @return tiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of tier name to tier binding.")

  public Map<String, V1alpha1LogicalTableSpecTiers> getTiers() {
    return tiers;
  }


  public void setTiers(Map<String, V1alpha1LogicalTableSpecTiers> tiers) {
    this.tiers = tiers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableSpec v1alpha1LogicalTableSpec = (V1alpha1LogicalTableSpec) o;
    return Objects.equals(this.tableName, v1alpha1LogicalTableSpec.tableName) &&
        Objects.equals(this.tiers, v1alpha1LogicalTableSpec.tiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tableName, tiers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableSpec {\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

