/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1LogicalTableSpecTiers
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T18:33:48.223Z[Etc/UTC]")
public class V1alpha1LogicalTableSpecTiers {
  public static final String SERIALIZED_NAME_DATABASE_CRD_NAME = "databaseCrdName";
  @SerializedName(SERIALIZED_NAME_DATABASE_CRD_NAME)
  private String databaseCrdName;


  public V1alpha1LogicalTableSpecTiers databaseCrdName(String databaseCrdName) {
    
    this.databaseCrdName = databaseCrdName;
    return this;
  }

   /**
   * Name of the Database CRD backing this tier.
   * @return databaseCrdName
  **/
  @ApiModelProperty(required = true, value = "Name of the Database CRD backing this tier.")

  public String getDatabaseCrdName() {
    return databaseCrdName;
  }


  public void setDatabaseCrdName(String databaseCrdName) {
    this.databaseCrdName = databaseCrdName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1LogicalTableSpecTiers v1alpha1LogicalTableSpecTiers = (V1alpha1LogicalTableSpecTiers) o;
    return Objects.equals(this.databaseCrdName, v1alpha1LogicalTableSpecTiers.databaseCrdName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseCrdName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1LogicalTableSpecTiers {\n");
    sb.append("    databaseCrdName: ").append(toIndentedString(databaseCrdName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

