/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TableProvisionJob spec.
 */
@ApiModel(description = "TableProvisionJob spec.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-13T23:58:00.641Z[Etc/UTC]")
public class V1alpha1TableProvisionJobSpec {
  public static final String SERIALIZED_NAME_DATABASE = "database";
  @SerializedName(SERIALIZED_NAME_DATABASE)
  private String database;

  public static final String SERIALIZED_NAME_TABLE = "table";
  @SerializedName(SERIALIZED_NAME_TABLE)
  private String table;


  public V1alpha1TableProvisionJobSpec database(String database) {
    
    this.database = database;
    return this;
  }

   /**
   * Database the table belongs to.
   * @return database
  **/
  @ApiModelProperty(required = true, value = "Database the table belongs to.")

  public String getDatabase() {
    return database;
  }


  public void setDatabase(String database) {
    this.database = database;
  }


  public V1alpha1TableProvisionJobSpec table(String table) {
    
    this.table = table;
    return this;
  }

   /**
   * Table name to provision.
   * @return table
  **/
  @ApiModelProperty(required = true, value = "Table name to provision.")

  public String getTable() {
    return table;
  }


  public void setTable(String table) {
    this.table = table;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1TableProvisionJobSpec v1alpha1TableProvisionJobSpec = (V1alpha1TableProvisionJobSpec) o;
    return Objects.equals(this.database, v1alpha1TableProvisionJobSpec.database) &&
        Objects.equals(this.table, v1alpha1TableProvisionJobSpec.table);
  }

  @Override
  public int hashCode() {
    return Objects.hash(database, table);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1TableProvisionJobSpec {\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

