apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Acl
metadata:
  name: sample-kafka-acl-1
spec:
  kind: KafkaTopic
  name: test-sink
  method: Read
  principal: User:ANONYMOUS

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Acl
metadata:
  name: sample-kafka-acl-2
spec:
  kind: KafkaTopic
  name: test-sink
  method: Write
  principal: User:ANONYMOUS

