## This template adds Flink support.

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: JobTemplate
metadata:
  name: flink-template
spec:
  yaml: |
    apiVersion: flink.apache.org/v1beta1
    kind: FlinkDeployment
    metadata:
      name: {{name}}
    spec:
      image: docker.io/library/hoptimator-flink-runner
      imagePullPolicy: Never
      flinkVersion: v1_16
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "1"
      serviceAccount: flink
      jobManager:
        resource:
          memory: "2048m"
          cpu: 0.1
      taskManager:
        resource:
          memory: "2048m"
          cpu: 0.1
      job:
        entryClass: com.linkedin.hoptimator.flink.runner.FlinkRunner
        args:
        - {{sql}}
        jarURI: local:///opt/hoptimator-flink-runner.jar
        parallelism: 1
        upgradeMode: stateless
        state: running

