apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Database
metadata:
  name: kafka-database
spec:
  schema: KAFKA
  url: jdbc:kafka://bootstrap.servers=localhost:9092
  dialect: Calcite

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: TableTemplate
metadata:
  name: kafka-template
spec:
  databases:
  - kafka-database
  yaml: |
    apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaTopic
    metadata:
      name: {{name}}
      labels:
        strimzi.io/cluster: one
    spec:
      topicName: {{table}}
      partitions: 1
      replicas: 1
      config:
        retention.ms: 7200000
        segment.bytes: 1073741824
  connector: |
    connector = kafka
    topic = {{table}}
    properties.bootstrap.servers = one-kafka-bootstrap.kafka.svc.cluster.local:9094
    value.format = json
    scan.startup.mode = earliest-offset
    key.fields = KEY
    key.format = raw
    value.fields-include = EXCEPT_KEY

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-database-existing-topic-1
  labels:
    strimzi.io/cluster: one
spec:
  topicName: existing-topic-1
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-database-existing-topic-2
  labels:
    strimzi.io/cluster: one
spec:
  topicName: existing-topic-2
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824


