
apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Subscription
metadata:
  name: products
spec:
  sql: SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
  database: RAWKAFKA

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Subscription
metadata:
  name: products-with-hints
spec:
  sql: SELECT "quantity", "product_id" AS KEY FROM INVENTORY."products_on_hand"
  database: RAWKAFKA
  hints:
    kafka.numPartitions: "7"

