apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Subscription
metadata:
  name: people
spec:
  sql: SELECT NAME FROM DATAGEN.PERSON
  database: RAWKAFKA

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Subscription
metadata:
  name: companies
spec:
  sql: SELECT NAME FROM DATAGEN.COMPANY
  database: RAWKAFKA

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Subscription
metadata:
  name: names
spec:
  sql: SELECT p.PAYLOAD || c.PAYLOAD FROM RAWKAFKA."people" p, RAWKAFKA."companies" c
  database: RAWKAFKA


