apiVersion: hoptimator.linkedin.com/v1alpha1
kind: TableTrigger
metadata:
  name: test-table-trigger
spec:
  schema: KAFKA
  table: existing-topic-1
  yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: test-table-trigger-job
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
      backoffLimit: 4

