apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Database
metadata:
  name: venice
spec:
  schema: VENICE
  url: jdbc:venice://clusters=venice-cluster0;router.url=http://localhost:7777
  dialect: Calcite

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: TableTemplate
metadata:
  name: venice-template
spec:
  databases:
    - venice
  connector: |
    connector = venice
    storeName = {{table}}
    partial-update-mode = true
    key.fields-prefix = {{keyPrefix:}}
    key.fields = {{keys:KEY}}
    key.type = {{keyType:PRIMITIVE}}
    value.fields-include = EXCEPT_KEY
