apiVersion: hoptimator.linkedin.com/v1alpha1
kind: Database
metadata:
  name: venice-cluster0
spec:
  schema: VENICE
  url: jdbc:venice://cluster=venice-cluster0;controller.url=http://localhost:5555
  dialect: Calcite

---

apiVersion: hoptimator.linkedin.com/v1alpha1
kind: TableTemplate
metadata:
  name: venice-template-cluster0
spec:
  databases:
    - venice-cluster0
  connector: |
    connector = venice
    cluster = {{database}}
    store = {{table}}
    properties.controller.url = http://localhost:5555

