apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-session-deployment
  namespace: flink
spec:
  image: docker.io/library/hoptimator-flink-runner
  imagePullPolicy: Never
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "6"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 0.1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 0.1
