apiVersion: v1
kind: Pod
metadata:
  name: hoptimator
spec:
  containers:
  - name: hoptimator
    image: docker.io/library/hoptimator
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    readinessProbe:
      exec:
        command: ["./hoptimator", "--run=./readiness-probe.sql"]
      timeoutSeconds: 30

