apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: hoptimator-operator
rules:
- apiGroups: ["hoptimator.linkedin.com"]
  resources: ["kafkatopics", "subscriptions"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["hoptimator.linkedin.com"]
  resources: ["kafkatopics/status", "subscriptions/status"]
  verbs: ["get", "patch"]
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments"]
  verbs: ["get", "update", "create"]

