/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkedin.hoptimator.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkedin.hoptimator.models.V1alpha1SubscriptionStatusResourceRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1SubscriptionStatusResources
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-06T00:58:39.977Z[Etc/UTC]")
public class V1alpha1SubscriptionStatusResources {
  public static final String SERIALIZED_NAME_RESOURCE_REF = "resourceRef";
  @SerializedName(SERIALIZED_NAME_RESOURCE_REF)
  private V1alpha1SubscriptionStatusResourceRef resourceRef;


  public V1alpha1SubscriptionStatusResources resourceRef(V1alpha1SubscriptionStatusResourceRef resourceRef) {
    
    this.resourceRef = resourceRef;
    return this;
  }

   /**
   * Get resourceRef
   * @return resourceRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1SubscriptionStatusResourceRef getResourceRef() {
    return resourceRef;
  }


  public void setResourceRef(V1alpha1SubscriptionStatusResourceRef resourceRef) {
    this.resourceRef = resourceRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SubscriptionStatusResources v1alpha1SubscriptionStatusResources = (V1alpha1SubscriptionStatusResources) o;
    return Objects.equals(this.resourceRef, v1alpha1SubscriptionStatusResources.resourceRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SubscriptionStatusResources {\n");
    sb.append("    resourceRef: ").append(toIndentedString(resourceRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

