/* Generated By:JavaCC: Do not edit this line. HoptimatorDdlParserImplConstants.java */
package com.linkedin.hoptimator.jdbc.ddl;

public interface HoptimatorDdlParserImplConstants {

  int EOF = 0;
  int A = 1;
  int ABS = 2;
  int ABSENT = 3;
  int ABSOLUTE = 4;
  int ACTION = 5;
  int ADA = 6;
  int ADD = 7;
  int ADMIN = 8;
  int AFTER = 9;
  int ALL = 10;
  int ALLOCATE = 11;
  int ALLOW = 12;
  int ALTER = 13;
  int ALWAYS = 14;
  int AND = 15;
  int ANY = 16;
  int APPLY = 17;
  int ARE = 18;
  int ARRAY = 19;
  int ARRAY_AGG = 20;
  int ARRAY_CONCAT_AGG = 21;
  int ARRAY_MAX_CARDINALITY = 22;
  int AS = 23;
  int ASOF = 24;
  int ASC = 25;
  int ASENSITIVE = 26;
  int ASSERTION = 27;
  int ASSIGNMENT = 28;
  int ASYMMETRIC = 29;
  int AT = 30;
  int ATOMIC = 31;
  int ATTRIBUTE = 32;
  int ATTRIBUTES = 33;
  int AUTHORIZATION = 34;
  int AVG = 35;
  int BEFORE = 36;
  int BEGIN = 37;
  int BEGIN_FRAME = 38;
  int BEGIN_PARTITION = 39;
  int BERNOULLI = 40;
  int BETWEEN = 41;
  int BIGINT = 42;
  int BINARY = 43;
  int BIT = 44;
  int BLOB = 45;
  int BOOLEAN = 46;
  int BOTH = 47;
  int BREADTH = 48;
  int BY = 49;
  int C = 50;
  int CALL = 51;
  int CALLED = 52;
  int CARDINALITY = 53;
  int CASCADE = 54;
  int CASCADED = 55;
  int CASE = 56;
  int CAST = 57;
  int CATALOG = 58;
  int CATALOG_NAME = 59;
  int CEIL = 60;
  int CEILING = 61;
  int CENTURY = 62;
  int CHAIN = 63;
  int CHAR = 64;
  int CHAR_LENGTH = 65;
  int CHARACTER = 66;
  int CHARACTER_LENGTH = 67;
  int CHARACTER_SET_CATALOG = 68;
  int CHARACTER_SET_NAME = 69;
  int CHARACTER_SET_SCHEMA = 70;
  int CHARACTERISTICS = 71;
  int CHARACTERS = 72;
  int CHECK = 73;
  int CLASSIFIER = 74;
  int CLASS_ORIGIN = 75;
  int CLOB = 76;
  int CLOSE = 77;
  int COALESCE = 78;
  int COBOL = 79;
  int COLLATE = 80;
  int COLLATION = 81;
  int COLLATION_CATALOG = 82;
  int COLLATION_NAME = 83;
  int COLLATION_SCHEMA = 84;
  int COLLECT = 85;
  int COLUMN = 86;
  int COLUMN_NAME = 87;
  int COMMAND_FUNCTION = 88;
  int COMMAND_FUNCTION_CODE = 89;
  int COMMIT = 90;
  int COMMITTED = 91;
  int CONDITION = 92;
  int CONDITIONAL = 93;
  int CONDITION_NUMBER = 94;
  int CONNECT = 95;
  int CONNECTION = 96;
  int CONNECTION_NAME = 97;
  int CONSTRAINT = 98;
  int CONSTRAINT_CATALOG = 99;
  int CONSTRAINT_NAME = 100;
  int CONSTRAINT_SCHEMA = 101;
  int CONSTRAINTS = 102;
  int CONSTRUCTOR = 103;
  int CONTAINS = 104;
  int CONTAINS_SUBSTR = 105;
  int CONTINUE = 106;
  int CONVERT = 107;
  int CORR = 108;
  int CORRESPONDING = 109;
  int COUNT = 110;
  int COVAR_POP = 111;
  int COVAR_SAMP = 112;
  int CREATE = 113;
  int CROSS = 114;
  int CUBE = 115;
  int CUME_DIST = 116;
  int CURRENT = 117;
  int CURRENT_CATALOG = 118;
  int CURRENT_DATE = 119;
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 120;
  int CURRENT_PATH = 121;
  int CURRENT_ROLE = 122;
  int CURRENT_ROW = 123;
  int CURRENT_SCHEMA = 124;
  int CURRENT_TIME = 125;
  int CURRENT_TIMESTAMP = 126;
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 127;
  int CURRENT_USER = 128;
  int CURSOR = 129;
  int CURSOR_NAME = 130;
  int CYCLE = 131;
  int DATA = 132;
  int DATABASE = 133;
  int DATE = 134;
  int DATE_DIFF = 135;
  int DATE_TRUNC = 136;
  int DATETIME = 137;
  int DATETIME_DIFF = 138;
  int DATETIME_INTERVAL_CODE = 139;
  int DATETIME_INTERVAL_PRECISION = 140;
  int DATETIME_TRUNC = 141;
  int DAY = 142;
  int DAYOFWEEK = 143;
  int DAYOFYEAR = 144;
  int DAYS = 145;
  int DEALLOCATE = 146;
  int DEC = 147;
  int DECADE = 148;
  int DECIMAL = 149;
  int DECLARE = 150;
  int DEFAULT_ = 151;
  int DEFAULTS = 152;
  int DEFERRABLE = 153;
  int DEFERRED = 154;
  int DEFINE = 155;
  int DEFINED = 156;
  int DEFINER = 157;
  int DEGREE = 158;
  int DELETE = 159;
  int DENSE_RANK = 160;
  int DEPTH = 161;
  int DEREF = 162;
  int DERIVED = 163;
  int DESC = 164;
  int DESCRIBE = 165;
  int DESCRIPTION = 166;
  int DESCRIPTOR = 167;
  int DETERMINISTIC = 168;
  int DIAGNOSTICS = 169;
  int DISALLOW = 170;
  int DISCONNECT = 171;
  int DISPATCH = 172;
  int DISTINCT = 173;
  int DOMAIN = 174;
  int DOT_FORMAT = 175;
  int DOUBLE = 176;
  int DOW = 177;
  int DOY = 178;
  int DROP = 179;
  int DYNAMIC = 180;
  int DYNAMIC_FUNCTION = 181;
  int DYNAMIC_FUNCTION_CODE = 182;
  int EACH = 183;
  int ELEMENT = 184;
  int ELSE = 185;
  int EMPTY = 186;
  int ENCODING = 187;
  int END = 188;
  int END_EXEC = 189;
  int END_FRAME = 190;
  int END_PARTITION = 191;
  int EPOCH = 192;
  int EQUALS = 193;
  int ERROR = 194;
  int ESCAPE = 195;
  int EVERY = 196;
  int EXCEPT = 197;
  int EXCEPTION = 198;
  int EXCLUDE = 199;
  int EXCLUDING = 200;
  int EXEC = 201;
  int EXECUTE = 202;
  int EXISTS = 203;
  int EXP = 204;
  int EXPLAIN = 205;
  int EXTEND = 206;
  int EXTERNAL = 207;
  int EXTRACT = 208;
  int FALSE = 209;
  int FETCH = 210;
  int FILTER = 211;
  int FINAL = 212;
  int FIRST = 213;
  int FIRST_VALUE = 214;
  int FLOAT = 215;
  int FLOOR = 216;
  int FOLLOWING = 217;
  int FOR = 218;
  int FORMAT = 219;
  int FOREIGN = 220;
  int FORTRAN = 221;
  int FOUND = 222;
  int FRAC_SECOND = 223;
  int FRAME_ROW = 224;
  int FREE = 225;
  int FRIDAY = 226;
  int FROM = 227;
  int FULL = 228;
  int FUNCTION = 229;
  int FUSION = 230;
  int G = 231;
  int GENERAL = 232;
  int GENERATED = 233;
  int GEOMETRY = 234;
  int GET = 235;
  int GLOBAL = 236;
  int GO = 237;
  int GOTO = 238;
  int GRANT = 239;
  int GRANTED = 240;
  int GROUP = 241;
  int GROUP_CONCAT = 242;
  int GROUPING = 243;
  int GROUPS = 244;
  int HAVING = 245;
  int HIERARCHY = 246;
  int HOLD = 247;
  int HOP = 248;
  int HOUR = 249;
  int HOURS = 250;
  int IDENTITY = 251;
  int IGNORE = 252;
  int ILIKE = 253;
  int IMMEDIATE = 254;
  int IMMEDIATELY = 255;
  int IMPLEMENTATION = 256;
  int IMPORT = 257;
  int IN = 258;
  int INCLUDE = 259;
  int INCLUDING = 260;
  int INCREMENT = 261;
  int INDICATOR = 262;
  int INITIAL = 263;
  int INITIALLY = 264;
  int INNER = 265;
  int INOUT = 266;
  int INPUT = 267;
  int INSENSITIVE = 268;
  int INSERT = 269;
  int INSTANCE = 270;
  int INSTANTIABLE = 271;
  int INT = 272;
  int INTEGER = 273;
  int INTERSECT = 274;
  int INTERSECTION = 275;
  int INTERVAL = 276;
  int INTO = 277;
  int INVOKER = 278;
  int IS = 279;
  int ISODOW = 280;
  int ISOYEAR = 281;
  int ISOLATION = 282;
  int JAVA = 283;
  int JOIN = 284;
  int JSON = 285;
  int JSON_ARRAY = 286;
  int JSON_ARRAYAGG = 287;
  int JSON_EXISTS = 288;
  int JSON_OBJECT = 289;
  int JSON_OBJECTAGG = 290;
  int JSON_QUERY = 291;
  int JSON_SCOPE = 292;
  int JSON_VALUE = 293;
  int K = 294;
  int KEY = 295;
  int KEY_MEMBER = 296;
  int KEY_TYPE = 297;
  int LABEL = 298;
  int LAG = 299;
  int LANGUAGE = 300;
  int LARGE = 301;
  int LAST = 302;
  int LAST_VALUE = 303;
  int LATERAL = 304;
  int LEAD = 305;
  int LEADING = 306;
  int LEFT = 307;
  int LENGTH = 308;
  int LEVEL = 309;
  int LIBRARY = 310;
  int LIKE = 311;
  int LIKE_REGEX = 312;
  int LIMIT = 313;
  int LN = 314;
  int LOCAL = 315;
  int LOCALTIME = 316;
  int LOCALTIMESTAMP = 317;
  int LOCATOR = 318;
  int LOWER = 319;
  int M = 320;
  int MAP = 321;
  int MATCH = 322;
  int MATCHED = 323;
  int MATCHES = 324;
  int MATCH_CONDITION = 325;
  int MATCH_NUMBER = 326;
  int MATCH_RECOGNIZE = 327;
  int MAX = 328;
  int MAXVALUE = 329;
  int MEASURE = 330;
  int MEASURES = 331;
  int MEMBER = 332;
  int MERGE = 333;
  int MESSAGE_LENGTH = 334;
  int MESSAGE_OCTET_LENGTH = 335;
  int MESSAGE_TEXT = 336;
  int METHOD = 337;
  int MICROSECOND = 338;
  int MILLISECOND = 339;
  int MILLENNIUM = 340;
  int MIN = 341;
  int MINUTE = 342;
  int MINUTES = 343;
  int MINVALUE = 344;
  int MOD = 345;
  int MODIFIES = 346;
  int MODULE = 347;
  int MONDAY = 348;
  int MONTH = 349;
  int MONTHS = 350;
  int MORE_ = 351;
  int MULTISET = 352;
  int MUMPS = 353;
  int NAME = 354;
  int NAMES = 355;
  int NANOSECOND = 356;
  int NATIONAL = 357;
  int NATURAL = 358;
  int NCHAR = 359;
  int NCLOB = 360;
  int NESTING = 361;
  int NEW = 362;
  int NEXT = 363;
  int NO = 364;
  int NONE = 365;
  int NORMALIZE = 366;
  int NORMALIZED = 367;
  int NOT = 368;
  int NTH_VALUE = 369;
  int NTILE = 370;
  int NULL = 371;
  int NULLABLE = 372;
  int NULLIF = 373;
  int NULLS = 374;
  int NUMBER = 375;
  int NUMERIC = 376;
  int OBJECT = 377;
  int OCCURRENCES_REGEX = 378;
  int OCTET_LENGTH = 379;
  int OCTETS = 380;
  int OF = 381;
  int OFFSET = 382;
  int OLD = 383;
  int OMIT = 384;
  int ON = 385;
  int ONE = 386;
  int ONLY = 387;
  int OPEN = 388;
  int OPTION = 389;
  int OPTIONS = 390;
  int OR = 391;
  int ORDER = 392;
  int ORDERING = 393;
  int ORDINAL = 394;
  int ORDINALITY = 395;
  int OTHERS = 396;
  int OUT = 397;
  int OUTER = 398;
  int OUTPUT = 399;
  int OVER = 400;
  int OVERLAPS = 401;
  int OVERLAY = 402;
  int OVERRIDING = 403;
  int PAD = 404;
  int PARAMETER = 405;
  int PARAMETER_MODE = 406;
  int PARAMETER_NAME = 407;
  int PARAMETER_ORDINAL_POSITION = 408;
  int PARAMETER_SPECIFIC_CATALOG = 409;
  int PARAMETER_SPECIFIC_NAME = 410;
  int PARAMETER_SPECIFIC_SCHEMA = 411;
  int PARTIAL = 412;
  int PARTITION = 413;
  int PASCAL = 414;
  int PASSING = 415;
  int PASSTHROUGH = 416;
  int PAST = 417;
  int PATH = 418;
  int PATTERN = 419;
  int PER = 420;
  int PERCENT = 421;
  int PERCENTILE_CONT = 422;
  int PERCENTILE_DISC = 423;
  int PERCENT_RANK = 424;
  int PERIOD = 425;
  int PERMUTE = 426;
  int PIVOT = 427;
  int PLACING = 428;
  int PLAN = 429;
  int PLI = 430;
  int PORTION = 431;
  int POSITION = 432;
  int POSITION_REGEX = 433;
  int POWER = 434;
  int PRECEDES = 435;
  int PRECEDING = 436;
  int PRECISION = 437;
  int PREPARE = 438;
  int PRESERVE = 439;
  int PREV = 440;
  int PRIMARY = 441;
  int PRIOR = 442;
  int PRIVILEGES = 443;
  int PROCEDURE = 444;
  int PUBLIC = 445;
  int QUALIFY = 446;
  int QUARTER = 447;
  int QUARTERS = 448;
  int RANGE = 449;
  int RANK = 450;
  int READ = 451;
  int READS = 452;
  int REAL = 453;
  int RECURSIVE = 454;
  int REF = 455;
  int REFERENCES = 456;
  int REFERENCING = 457;
  int REGR_AVGX = 458;
  int REGR_AVGY = 459;
  int REGR_COUNT = 460;
  int REGR_INTERCEPT = 461;
  int REGR_R2 = 462;
  int REGR_SLOPE = 463;
  int REGR_SXX = 464;
  int REGR_SXY = 465;
  int REGR_SYY = 466;
  int RELATIVE = 467;
  int RELEASE = 468;
  int REPEATABLE = 469;
  int REPLACE = 470;
  int RESET = 471;
  int RESPECT = 472;
  int RESTART = 473;
  int RESTRICT = 474;
  int RESULT = 475;
  int RETURN = 476;
  int RETURNED_CARDINALITY = 477;
  int RETURNED_LENGTH = 478;
  int RETURNED_OCTET_LENGTH = 479;
  int RETURNED_SQLSTATE = 480;
  int RETURNING = 481;
  int RETURNS = 482;
  int REVOKE = 483;
  int RIGHT = 484;
  int RLIKE = 485;
  int ROLE = 486;
  int ROLLBACK = 487;
  int ROLLUP = 488;
  int ROUTINE = 489;
  int ROUTINE_CATALOG = 490;
  int ROUTINE_NAME = 491;
  int ROUTINE_SCHEMA = 492;
  int ROW = 493;
  int ROW_COUNT = 494;
  int ROW_NUMBER = 495;
  int ROWS = 496;
  int RUNNING = 497;
  int SAFE_CAST = 498;
  int SAFE_OFFSET = 499;
  int SAFE_ORDINAL = 500;
  int SATURDAY = 501;
  int SAVEPOINT = 502;
  int SCALAR = 503;
  int SCALE = 504;
  int SCHEMA = 505;
  int SCHEMA_NAME = 506;
  int SCOPE = 507;
  int SCOPE_CATALOGS = 508;
  int SCOPE_NAME = 509;
  int SCOPE_SCHEMA = 510;
  int SCROLL = 511;
  int SEARCH = 512;
  int SECOND = 513;
  int SECONDS = 514;
  int SECTION = 515;
  int SECURITY = 516;
  int SEEK = 517;
  int SELECT = 518;
  int SELF = 519;
  int SENSITIVE = 520;
  int SEPARATOR = 521;
  int SEQUENCE = 522;
  int SERIALIZABLE = 523;
  int SERVER = 524;
  int SERVER_NAME = 525;
  int SESSION = 526;
  int SESSION_USER = 527;
  int SET = 528;
  int SETS = 529;
  int SET_MINUS = 530;
  int SHOW = 531;
  int SIMILAR = 532;
  int SIMPLE = 533;
  int SIZE = 534;
  int SKIP_ = 535;
  int SMALLINT = 536;
  int SOME = 537;
  int SOURCE = 538;
  int SPACE = 539;
  int SPECIFIC = 540;
  int SPECIFIC_NAME = 541;
  int SPECIFICTYPE = 542;
  int SQL = 543;
  int SQLEXCEPTION = 544;
  int SQLSTATE = 545;
  int SQLWARNING = 546;
  int SQL_BIGINT = 547;
  int SQL_BINARY = 548;
  int SQL_BIT = 549;
  int SQL_BLOB = 550;
  int SQL_BOOLEAN = 551;
  int SQL_CHAR = 552;
  int SQL_CLOB = 553;
  int SQL_DATE = 554;
  int SQL_DECIMAL = 555;
  int SQL_DOUBLE = 556;
  int SQL_FLOAT = 557;
  int SQL_INTEGER = 558;
  int SQL_INTERVAL_DAY = 559;
  int SQL_INTERVAL_DAY_TO_HOUR = 560;
  int SQL_INTERVAL_DAY_TO_MINUTE = 561;
  int SQL_INTERVAL_DAY_TO_SECOND = 562;
  int SQL_INTERVAL_HOUR = 563;
  int SQL_INTERVAL_HOUR_TO_MINUTE = 564;
  int SQL_INTERVAL_HOUR_TO_SECOND = 565;
  int SQL_INTERVAL_MINUTE = 566;
  int SQL_INTERVAL_MINUTE_TO_SECOND = 567;
  int SQL_INTERVAL_MONTH = 568;
  int SQL_INTERVAL_SECOND = 569;
  int SQL_INTERVAL_YEAR = 570;
  int SQL_INTERVAL_YEAR_TO_MONTH = 571;
  int SQL_LONGVARBINARY = 572;
  int SQL_LONGVARCHAR = 573;
  int SQL_LONGVARNCHAR = 574;
  int SQL_NCHAR = 575;
  int SQL_NCLOB = 576;
  int SQL_NUMERIC = 577;
  int SQL_NVARCHAR = 578;
  int SQL_REAL = 579;
  int SQL_SMALLINT = 580;
  int SQL_TIME = 581;
  int SQL_TIMESTAMP = 582;
  int SQL_TINYINT = 583;
  int SQL_TSI_DAY = 584;
  int SQL_TSI_FRAC_SECOND = 585;
  int SQL_TSI_HOUR = 586;
  int SQL_TSI_MICROSECOND = 587;
  int SQL_TSI_MINUTE = 588;
  int SQL_TSI_MONTH = 589;
  int SQL_TSI_QUARTER = 590;
  int SQL_TSI_SECOND = 591;
  int SQL_TSI_WEEK = 592;
  int SQL_TSI_YEAR = 593;
  int SQL_VARBINARY = 594;
  int SQL_VARCHAR = 595;
  int SQRT = 596;
  int START = 597;
  int STATE = 598;
  int STATEMENT = 599;
  int STATIC = 600;
  int STDDEV_POP = 601;
  int STDDEV_SAMP = 602;
  int STREAM = 603;
  int STRING_AGG = 604;
  int STRUCTURE = 605;
  int STYLE = 606;
  int SUBCLASS_ORIGIN = 607;
  int SUBMULTISET = 608;
  int SUBSET = 609;
  int SUBSTITUTE = 610;
  int SUBSTRING = 611;
  int SUBSTRING_REGEX = 612;
  int SUCCEEDS = 613;
  int SUM = 614;
  int SUNDAY = 615;
  int SYMMETRIC = 616;
  int SYSTEM = 617;
  int SYSTEM_TIME = 618;
  int SYSTEM_USER = 619;
  int TABLE = 620;
  int TABLE_NAME = 621;
  int TABLESAMPLE = 622;
  int TEMPORARY = 623;
  int THEN = 624;
  int THURSDAY = 625;
  int TIES = 626;
  int TIME = 627;
  int TIME_DIFF = 628;
  int TIME_TRUNC = 629;
  int TIMESTAMP = 630;
  int TIMESTAMPADD = 631;
  int TIMESTAMPDIFF = 632;
  int TIMESTAMP_DIFF = 633;
  int TIMESTAMP_TRUNC = 634;
  int TIMEZONE_HOUR = 635;
  int TIMEZONE_MINUTE = 636;
  int TINYINT = 637;
  int TO = 638;
  int TOP_LEVEL_COUNT = 639;
  int TRAILING = 640;
  int TRANSACTION = 641;
  int TRANSACTIONS_ACTIVE = 642;
  int TRANSACTIONS_COMMITTED = 643;
  int TRANSACTIONS_ROLLED_BACK = 644;
  int TRANSFORM = 645;
  int TRANSFORMS = 646;
  int TRANSLATE = 647;
  int TRANSLATE_REGEX = 648;
  int TRANSLATION = 649;
  int TREAT = 650;
  int TRIGGER = 651;
  int TRIGGER_CATALOG = 652;
  int TRIGGER_NAME = 653;
  int TRIGGER_SCHEMA = 654;
  int TRIM = 655;
  int TRIM_ARRAY = 656;
  int TRUE = 657;
  int TRUNCATE = 658;
  int TRY_CAST = 659;
  int TUESDAY = 660;
  int TUMBLE = 661;
  int TYPE = 662;
  int UESCAPE = 663;
  int UNBOUNDED = 664;
  int UNCOMMITTED = 665;
  int UNCONDITIONAL = 666;
  int UNDER = 667;
  int UNION = 668;
  int UNIQUE = 669;
  int UNKNOWN = 670;
  int UNPIVOT = 671;
  int UNNAMED = 672;
  int UNNEST = 673;
  int UNSIGNED = 674;
  int UPDATE = 675;
  int UPPER = 676;
  int UPSERT = 677;
  int USAGE = 678;
  int USER = 679;
  int USER_DEFINED_TYPE_CATALOG = 680;
  int USER_DEFINED_TYPE_CODE = 681;
  int USER_DEFINED_TYPE_NAME = 682;
  int USER_DEFINED_TYPE_SCHEMA = 683;
  int USING = 684;
  int UTF8 = 685;
  int UTF16 = 686;
  int UTF32 = 687;
  int UUID = 688;
  int VALUE = 689;
  int VALUES = 690;
  int VALUE_OF = 691;
  int VAR_POP = 692;
  int VAR_SAMP = 693;
  int VARBINARY = 694;
  int VARCHAR = 695;
  int VARIANT = 696;
  int VARYING = 697;
  int VERSION = 698;
  int VERSIONING = 699;
  int VIEW = 700;
  int WEDNESDAY = 701;
  int WEEK = 702;
  int WEEKS = 703;
  int WHEN = 704;
  int WHENEVER = 705;
  int WHERE = 706;
  int WIDTH_BUCKET = 707;
  int WINDOW = 708;
  int WITH = 709;
  int WITHIN = 710;
  int WITHOUT = 711;
  int WORK = 712;
  int WRAPPER = 713;
  int WRITE = 714;
  int XML = 715;
  int YEAR = 716;
  int YEARS = 717;
  int ZONE = 718;
  int IF = 719;
  int MATERIALIZED = 720;
  int STORED = 721;
  int VIRTUAL = 722;
  int JAR = 723;
  int FILE = 724;
  int ARCHIVE = 725;
  int REFRESHED = 726;
  int UNSIGNED_INTEGER_LITERAL = 727;
  int APPROX_NUMERIC_LITERAL = 728;
  int DECIMAL_NUMERIC_LITERAL = 729;
  int EXPONENT = 730;
  int HEXDIGIT = 731;
  int WHITESPACE = 732;
  int BINARY_STRING_LITERAL = 733;
  int QUOTED_STRING = 734;
  int PREFIXED_STRING_LITERAL = 735;
  int UNICODE_STRING_LITERAL = 736;
  int C_STYLE_ESCAPED_STRING_LITERAL = 737;
  int CHARSETNAME = 738;
  int BIG_QUERY_DOUBLE_QUOTED_STRING = 739;
  int BIG_QUERY_QUOTED_STRING = 740;
  int UNICODE_QUOTED_ESCAPE_CHAR = 741;
  int LPAREN = 742;
  int RPAREN = 743;
  int LBRACE_D = 744;
  int LBRACE_T = 745;
  int LBRACE_TS = 746;
  int LBRACE_FN = 747;
  int LBRACE = 748;
  int RBRACE = 749;
  int LBRACKET = 750;
  int RBRACKET = 751;
  int SEMICOLON = 752;
  int DOT = 753;
  int COMMA = 754;
  int EQ = 755;
  int GT = 756;
  int LT = 757;
  int HOOK = 758;
  int COLON = 759;
  int LE = 760;
  int GE = 761;
  int NE = 762;
  int NE2 = 763;
  int PLUS = 764;
  int MINUS = 765;
  int LAMBDA = 766;
  int STAR = 767;
  int SLASH = 768;
  int PERCENT_REMAINDER = 769;
  int CONCAT = 770;
  int NAMED_ARGUMENT_ASSIGNMENT = 771;
  int DOUBLE_PERIOD = 772;
  int QUOTE = 773;
  int DOUBLE_QUOTE = 774;
  int VERTICAL_BAR = 775;
  int CARET = 776;
  int DOLLAR = 777;
  int HINT_BEG = 783;
  int COMMENT_END = 784;
  int SINGLE_LINE_COMMENT = 787;
  int FORMAL_COMMENT = 788;
  int MULTI_LINE_COMMENT = 789;
  int BRACKET_QUOTED_IDENTIFIER = 791;
  int QUOTED_IDENTIFIER = 792;
  int BACK_QUOTED_IDENTIFIER = 793;
  int BIG_QUERY_BACK_QUOTED_IDENTIFIER = 794;
  int HYPHENATED_IDENTIFIER = 795;
  int IDENTIFIER = 796;
  int COLLATION_ID = 797;
  int UNICODE_QUOTED_IDENTIFIER = 798;
  int LETTER = 799;
  int DIGIT = 800;
  int BEL = 801;

  int DEFAULT = 0;
  int DQID = 1;
  int BTID = 2;
  int BQID = 3;
  int BQHID = 4;
  int IN_FORMAL_COMMENT = 5;
  int IN_MULTI_LINE_COMMENT = 6;

  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_AGG\"",
    "\"ARRAY_CONCAT_AGG\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASOF\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTAINS_SUBSTR\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATE_DIFF\"",
    "\"DATE_TRUNC\"",
    "\"DATETIME\"",
    "\"DATETIME_DIFF\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DATETIME_TRUNC\"",
    "\"DAY\"",
    "\"DAYOFWEEK\"",
    "\"DAYOFYEAR\"",
    "\"DAYS\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOT\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FRIDAY\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUP_CONCAT\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOP\"",
    "\"HOUR\"",
    "\"HOURS\"",
    "\"IDENTITY\"",
    "\"IGNORE\"",
    "\"ILIKE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDE\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"JSON_SCOPE\"",
    "\"JSON_VALUE\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_CONDITION\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINUTES\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONDAY\"",
    "\"MONTH\"",
    "\"MONTHS\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINAL\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUALIFY\"",
    "\"QUARTER\"",
    "\"QUARTERS\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESPECT\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"RLIKE\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SAFE_CAST\"",
    "\"SAFE_OFFSET\"",
    "\"SAFE_ORDINAL\"",
    "\"SATURDAY\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECONDS\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEPARATOR\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRING_AGG\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SUNDAY\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"THURSDAY\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIME_DIFF\"",
    "\"TIME_TRUNC\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMESTAMP_DIFF\"",
    "\"TIMESTAMP_TRUNC\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TRY_CAST\"",
    "\"TUESDAY\"",
    "\"TUMBLE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNPIVOT\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UNSIGNED\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"UUID\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARIANT\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIEW\"",
    "\"WEDNESDAY\"",
    "\"WEEK\"",
    "\"WEEKS\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"YEARS\"",
    "\"ZONE\"",
    "\"IF\"",
    "\"MATERIALIZED\"",
    "\"STORED\"",
    "\"VIRTUAL\"",
    "\"JAR\"",
    "\"FILE\"",
    "\"ARCHIVE\"",
    "\"REFRESHED\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<C_STYLE_ESCAPED_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<BIG_QUERY_DOUBLE_QUOTED_STRING>",
    "<BIG_QUERY_QUOTED_STRING>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"->\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*+\"",
    "\"*/\"",
    "<token of kind 785>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<token of kind 790>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<BIG_QUERY_BACK_QUOTED_IDENTIFIER>",
    "<HYPHENATED_IDENTIFIER>",
    "<IDENTIFIER>",
    "<COLLATION_ID>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
