name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build
      run: make build
    - name: Create K8s Kind Cluster
      uses: helm/kind-action@v1.4.0
      with:
        cluster_name: 'kind'
    - name: Load Docker Images
      run: |
        kind load docker-image hoptimator
        kind load docker-image hoptimator-flink-runner
    - name: Deploy Dev Environment
      run: make deploy-dev-environment
    - name: Deploy Hoptimator
      run: make deploy deploy-samples
    - name: Wait for Readiness
      run: kubectl wait pod hoptimator --for condition=Ready --timeout=5m || kubectl describe pod hoptimator
    - name: Integration Tests
      run: make integration-tests

